name: Deploy Backend to EC2

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
        
    - name: Build backend with Gradle
      working-directory: ./backend
      run: |
        chmod +x ./gradlew
        ./gradlew build -x test --no-daemon
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Upload JAR to S3
      run: |
        ls -la backend/build/libs/
        aws s3 cp backend/build/libs/api-0.0.1-SNAPSHOT.jar s3://${{ secrets.S3_BUCKET }}/snippethub-backend.jar
        
    - name: Deploy to EC2
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=[
            "sudo systemctl stop snippethub-backend || true",
            "mkdir -p ~/app",
            "aws s3 cp s3://${{ secrets.S3_BUCKET }}/snippethub-backend.jar ~/app/snippethub-backend.jar",
            "sudo tee /etc/systemd/system/snippethub-backend.service > /dev/null << \"EOF\"",
            "[Unit]",
            "Description=SnippetHub Backend Application",
            "After=network.target",
            "",
            "[Service]",
            "Type=simple",
            "User=ubuntu",
            "WorkingDirectory=/home/ubuntu/app",
            "ExecStart=/usr/bin/java -jar /home/ubuntu/app/snippethub-backend.jar",
            "Restart=always",
            "RestartSec=10",
            "",
            "[Install]",
            "WantedBy=multi-user.target",
            "EOF",
            "sudo systemctl daemon-reload",
            "sudo systemctl enable snippethub-backend",
            "sudo systemctl start snippethub-backend",
            "sudo systemctl status snippethub-backend"
          ]' \
          --region ${{ secrets.AWS_REGION }}
        
    - name: Verify deployment
      run: |
        sleep 30
        curl -f http://${{ secrets.EC2_HOST }}:8080/actuator/health || exit 1
        
    - name: Deploy success
      run: echo "Backend deployed successfully to http://${{ secrets.EC2_HOST }}:8080"
