name: Deploy Backend to EC2

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
        
    - name: Build backend with Gradle
      working-directory: ./backend
      run: |
        chmod +x ./gradlew
        ./gradlew build -x test --no-daemon
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Upload JAR to S3
      run: |
        ls -la backend/build/libs/
        aws s3 cp backend/build/libs/api-0.0.1-SNAPSHOT.jar s3://${{ secrets.S3_BUCKET }}/snippethub-backend.jar
        
    - name: Setup SSH
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > /tmp/snippethub-key.pem
        chmod 400 /tmp/snippethub-key.pem
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true
        ssh-keyscan -H 10.0.3.74 >> ~/.ssh/known_hosts 2>/dev/null || true
        ls -la /tmp/snippethub-key.pem
        echo "SSH key content (first 50 chars):"
        head -c 50 /tmp/snippethub-key.pem
        echo ""
        echo "SSH key content (last 50 chars):"
        tail -c 50 /tmp/snippethub-key.pem
        echo ""
        echo "SSH key line count:"
        wc -l /tmp/snippethub-key.pem
        echo "SSH key fingerprint:"
        ssh-keygen -lf /tmp/snippethub-key.pem || echo "Failed to get fingerprint"
        echo "SSH key setup completed"
        
    - name: Test SSH connection
      run: |
        echo "Testing SSH connection to NAT instance..."
        echo "SSH key fingerprint:"
        ssh-keygen -lf /tmp/snippethub-key.pem || echo "Failed to get fingerprint"
        echo "Attempting SSH connection..."
        ssh -v -o StrictHostKeyChecking=no -i /tmp/snippethub-key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "echo 'NAT instance connection successful'"
        
    - name: Deploy to EC2
      run: |
        # Create deployment script
                 cat > deploy.sh << 'SCRIPTEOF'
         #!/bin/bash
         set -e
         echo "Starting deployment script..."
         
         echo "Stopping existing service..."
         sudo systemctl stop snippethub-backend || echo "Service was not running"
         
         echo "Creating app directory..."
         mkdir -p ~/app
         
         echo "Downloading JAR from S3..."
         aws s3 cp s3://${{ secrets.S3_BUCKET }}/snippethub-backend.jar ~/app/snippethub-backend.jar
        
        sudo tee /etc/systemd/system/snippethub-backend.service > /dev/null << 'SERVICEEOF'
        [Unit]
        Description=SnippetHub Backend Application
        After=network.target
        
        [Service]
        Type=simple
        User=ubuntu
        WorkingDirectory=/home/ubuntu/app
        ExecStart=/usr/bin/java -jar /home/ubuntu/app/snippethub-backend.jar
        Restart=always
        RestartSec=10
        
        [Install]
        WantedBy=multi-user.target
        SERVICEEOF
        
                 echo "Creating systemd service file..."
         sudo tee /etc/systemd/system/snippethub-backend.service > /dev/null << 'SERVICEEOF'
         [Unit]
         Description=SnippetHub Backend Application
         After=network.target
         
         [Service]
         Type=simple
         User=ubuntu
         WorkingDirectory=/home/ubuntu/app
         ExecStart=/usr/bin/java -jar /home/ubuntu/app/snippethub-backend.jar
         Restart=always
         RestartSec=10
         
         [Install]
         WantedBy=multi-user.target
         SERVICEEOF
         
         echo "Reloading systemd..."
         sudo systemctl daemon-reload
         
         echo "Enabling service..."
         sudo systemctl enable snippethub-backend
         
         echo "Starting service..."
         sudo systemctl start snippethub-backend
         
         echo "Checking service status..."
         sudo systemctl status snippethub-backend
         
         echo "Deployment completed successfully!"
        SCRIPTEOF
        
                 # Copy script to NAT instance
         scp -o StrictHostKeyChecking=no -i /tmp/snippethub-key.pem deploy.sh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/
         
         # Execute script on backend EC2 with timeout and keep-alive
         ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -i /tmp/snippethub-key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -i ~/.ssh/snippethub-KeyPair.pem ${{ secrets.EC2_USERNAME }}@10.0.3.74 'bash -s' < ~/deploy.sh"
        
    - name: Verify deployment
      run: |
        sleep 30
        echo "Checking ALB health endpoint..."
        curl -f https://snippethub-alb-120890630.ap-northeast-2.elb.amazonaws.com/actuator/health || exit 1
        
    - name: Deploy success
      run: echo "Backend deployed successfully to ALB"
